[2025-03-25T00:39:08.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-25T00:39:08.173+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: projeto5.dsa_carrega_dados scheduled__2025-03-25T00:38:00+00:00 [queued]>
[2025-03-25T00:39:08.176+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: projeto5.dsa_carrega_dados scheduled__2025-03-25T00:38:00+00:00 [queued]>
[2025-03-25T00:39:08.176+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-25T00:39:08.181+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dsa_carrega_dados> on 2025-03-25 00:38:00+00:00
[2025-03-25T00:39:08.184+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T00:39:08.184+0000] {standard_task_runner.py:63} INFO - Started process 227 to run task
[2025-03-25T00:39:08.185+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'projeto5', 'dsa_carrega_dados', 'scheduled__2025-03-25T00:38:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/projeto5.py', '--cfg-path', '/tmp/tmphod4mqai']
[2025-03-25T00:39:08.186+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask dsa_carrega_dados
[2025-03-25T00:39:08.203+0000] {task_command.py:426} INFO - Running <TaskInstance: projeto5.dsa_carrega_dados scheduled__2025-03-25T00:38:00+00:00 [running]> on host ecff7bb19c75
[2025-03-25T00:39:08.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Science Academy' AIRFLOW_CTX_DAG_ID='projeto5' AIRFLOW_CTX_TASK_ID='dsa_carrega_dados' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T00:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T00:38:00+00:00'
[2025-03-25T00:39:08.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-25T00:39:08.253+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-25T00:39:08.254+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-25T00:39:08.258+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=projeto5, task_id=dsa_carrega_dados, run_id=scheduled__2025-03-25T00:38:00+00:00, execution_date=20250325T003800, start_date=20250325T003908, end_date=20250325T003908
[2025-03-25T00:39:08.283+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-25T00:39:08.291+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:39:08.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
